web_server:
  build: web/
  tty: true
  ports:
    - 8000:80
  container_name: web_server
  volumes:
    - ../:/var/www/html
  links:
    - mysql_server:mysql

mysql_server:
  build: mysql/
  ports:
    - 3306:3306
  container_name: mysql_server
  environment:
    - MYSQL_ROOT_PASSWORD=w@rp

myadmin_server:
  mage: phpmyadmin/phpmyadmin
  links: 
    - mysql_server:mysql
  ports:
    - 8888:80
  restart: always  
  container_name: myadmin_server   

